# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blackboard
tagline:             'Perspectives and thoughts from Zhenhua Yao'
description:         '<b>Blackboard</b> - personal memo of random stuff on software development.'
url:                 http://yaozhenhua.github.io
baseurl:             ''
paginate:            5
markdown:            redcarpet
redcarpet:
  extensions:        ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

# About/contact
author:
  name:              Zhenhua Yao
  url:               https://twitter.com/yaozhenhua
  email:             yaozhenhua@users.noreply.github.com

# Custom vars
version:             1.0.0

pages_list:
  About:             '/about'
  Archive:           '/archive'
  Feed:              '/atom.xml'
