# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Blackboard
tagline:             'Perspectives and thoughts from Zhenhua Yao'
description:         'Site description.'
url:                 http://yaozhenhua.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Zhenhua
  url:               https://twitter.com/yaozhenhua
  email:             yaozhenhua@users.noreply.github.com

# Custom vars
version:             1.0.0

pages_list:
  About:             '/about'
  Archive:           '/archive'
  Feed:              '/atom.xml'
